Feature yk - 매출중량 계산 메서드 추가
Yongson-Kim/TestApi pull request #7
Opened 2020-10-07 06:40 UTC by Yongson-Kim

2020-10-07 06:43 UTC, xxggdan requested changes
수정 바랍니다.

2020-10-07 06:43 UTC, xxggdan commented on MyTestApi/Controllers/HelloController.cs
> +        }
계산 로직이 없습니다.

2020-10-07 06:43 UTC, xxggdan commented on MyTestApi/Controllers/HelloController.cs
> +            // yk작업2
주석 정리가 필요합니다.

2020-10-20 23:37 UTC, closed without merging

2020-10-20 23:37 UTC, Yongson-Kim commented
재작업하겠습니다.